In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1) Using tf functions

In [33]:
# Creating variables
x = tf.Variable(10, dtype=tf.float64)

In [34]:
# Function
y = x ** 2
delta = 0.2

In [35]:
# Add to variables
x.assign_add(delta)

<tf.Variable 'UnreadVariable' shape=() dtype=float64, numpy=10.2>

In [36]:
for i in range(10):
    x.assign_add(delta)

In [37]:
x

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=12.199999999999992>

## 2) Gradient Descent

In [67]:
x = tf.Variable(40.0, dtype=tf.float64)
def quadratic_function(x):
    return x * x

In [148]:
alpha = 0.001
epochs = 1000

In [140]:
x

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=-2.9999999147689316>

In [141]:
with tf.GradientTape() as tape:
    y = quadratic_function(x)
tape.gradient(y, x)

<tf.Tensor: shape=(), dtype=float64, numpy=-5.999999829537863>

In [142]:
for i in range(epochs):
    with tf.GradientTape() as tape:
        y = quadratic_function(x)
    g = tape.gradient(y, x)
    x.assign_add(-alpha * g)

In [143]:
x

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=-5.048901928206776e-09>

In [165]:
alpha = 0.005
epochs = 2000

In [174]:
# Multivariables
x = tf.Variable(10.0, dtype=tf.float64)
y = tf.Variable(10.0, dtype=tf.float64)
def f(x, y):
    return ((x + 3) * (x + 3)) + ((y + 3) * (y + 3)) + 3

In [175]:
with tf.GradientTape(persistent=True) as tape:
    z = f(x, y)
    theta = [x, y]
tape.gradient(z, theta)

[<tf.Tensor: shape=(), dtype=float64, numpy=26.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=26.0>]

In [176]:
# Optimization
for i in range(epochs):
    with tf.GradientTape() as tape:
        z = f(x, y)
    theta = [x, y]
    g = tape.gradient(z, theta)
    x.assign_add(-alpha * g[0])
    y.assign_add(-alpha * g[1])

In [177]:
theta

[<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=-2.999999975771166>,
 <tf.Variable 'Variable:0' shape=() dtype=float64, numpy=-2.999999975771166>]

In [178]:
# using tf optimizer 

In [184]:
# Define as variáveis da função
x = tf.Variable(0.0, name='x')
y = tf.Variable(0.0, name='y')

# Define a função a ser otimizada
def quadratic_function(x, y):
    return (x + 3)**2 + (y + 3)**2

# Define a taxa de aprendizado e o número de iterações
learning_rate = 0.1
num_iterations = 100

# Define o otimizador
optimizer = tf.optimizers.SGD(learning_rate=learning_rate)

# Executa as iterações de otimização
for i in range(num_iterations):
    with tf.GradientTape() as tape:
        # Avalia a função nas variáveis x e y
        z = quadratic_function(x, y)
    # Calcula o gradiente da função em relação a x e y
    gradients = tape.gradient(z, [x, y])
    # Atualiza os valores de x e y usando o gradiente e a taxa de aprendizado
    optimizer.apply_gradients(zip(gradients, [x, y]))

# Imprime o valor final de x e y
print('Valor final de x:', x.numpy())
print('Valor final de y:', y.numpy())

Valor final de x: -2.9999995
Valor final de y: -2.9999995
